export const MY_CONSTANTS = {
    INSUFFICIENT_CREDITS: "INSUFFICIENT_CREDITS",
    GENERATION_STARTED: "GENERATION_STARTED",
    GENERATION_FAILED: "GENERATION_FAILED",
    PENDING: "PENDING",
    READY: "READY",
    FAILED: "FAILED", 
}
